# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Code\KeyManager\keyAddForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_keyAddForm(object):
    def setupUi(self, keyAddForm):
        keyAddForm.setObjectName("keyAddForm")
        keyAddForm.resize(400, 84)
        self.label = QtWidgets.QLabel(keyAddForm)
        self.label.setGeometry(QtCore.QRect(20, 10, 351, 21))
        self.label.setObjectName("label")
        self.cbKeyType = QtWidgets.QComboBox(keyAddForm)
        self.cbKeyType.setGeometry(QtCore.QRect(80, 10, 111, 22))
        self.cbKeyType.setObjectName("cbKeyType")
        self.sbKeyCount = QtWidgets.QSpinBox(keyAddForm)
        self.sbKeyCount.setGeometry(QtCore.QRect(290, 10, 51, 22))
        self.sbKeyCount.setMaximum(999)
        self.sbKeyCount.setObjectName("sbKeyCount")
        self.btnOK = QtWidgets.QPushButton(keyAddForm)
        self.btnOK.setGeometry(QtCore.QRect(270, 50, 71, 23))
        self.btnOK.setObjectName("btnOK")
        self.label_2 = QtWidgets.QLabel(keyAddForm)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 171, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(keyAddForm)
        QtCore.QMetaObject.connectSlotsByName(keyAddForm)

    def retranslateUi(self, keyAddForm):
        _translate = QtCore.QCoreApplication.translate
        keyAddForm.setWindowTitle(_translate("keyAddForm", "新增密钥"))
        self.label.setText(_translate("keyAddForm", "密钥类型:                          密钥数量:"))
        self.btnOK.setText(_translate("keyAddForm", "确定"))
        self.label_2.setText(_translate("keyAddForm", "-- by renrendoushikexuejia"))
